services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.production
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/blogify
      REDIS_URI: redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args: # automatically takes from .env adjacent to compose.yaml
        VITE_API_URI: ${VITE_API_URI}
        VITE_TINYMCE_API_KEY: ${VITE_TINYMCE_API_KEY}
    depends_on:
      - backend
    ports:
      - "4173:80"
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
