services:
  redis:
    image: "redis:alpine"
    # Port 6379 is exposed internally by default

  backend:
    build: .
    env_file:
      - .env.production.local
    depends_on:
      - redis
    ports:
      - 3000:3000
