name: "Frontend: Production Deploy"

on:
  push:
    branches: [main]

jobs:
  deploy_s3:
    name: "Build and Sync to S3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build Frontend
        env:
          VITE_API_URI: https://blogify.anandshete.dev/api/v1
          VITE_TINYMCE_API_KEY: 66q5lb1qtq3kp4bjjikt2grg0dx5ha5tl07kpgzzfy0qv4eo
        run: |
          cd ./frontend 
          npm ci 
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - run: aws s3 sync ./frontend/dist/ s3://blogify-frontend-static/dist --delete
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
