name: Continuous Deployment to EC2

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Deploy backend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies and zip
        run: |
          cd ./backend
          npm ci --omit=dev
          zip -r ../deploy.zip .

      - name: Deploy to EC2 via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./deploy.zip"
          TARGET: "/home/${{ secrets.EC2_USER }}/blogify_tmp/"

      - name: Unzip and run deploy script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/blogify
            unzip -o /home/${{ secrets.EC2_USER }}/blogify_tmp/deploy.zip -d /home/${{ secrets.EC2_USER }}/blogify
            rm -rf /home/${{ secrets.EC2_USER }}/blogify_tmp
            chmod +x /home/${{ secrets.EC2_USER }}/blogify/deploy.sh
            /home/${{ secrets.EC2_USER }}/blogify/deploy.sh

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install && npm run build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - run: aws s3 sync dist/ s3://your-bucket-name --delete
      # Recommended: Invalidate CloudFront cache so changes show immediately
      - run:
          aws cloudfront create-invalidation --distribution-id YOUR_DIST_ID --paths
          "/*"
