name: Continuous Deployment to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Deploy to EC2 via SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./backend/"
          TARGET: "/home/${{ secrets.EC2_USER }}/blogify/"
          EXCLUDE: "node_modules/, .git/, *.env, *.log"
          SCRIPT_BEFORE: mkdir -p /home/${{ secrets.EC2_USER }}/blogify

      - name: Run deploy script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/${{ secrets.EC2_USER }}/blogify/deploy.sh
            /home/${{ secrets.EC2_USER }}/blogify/deploy.sh
